<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            // --- Smartphones ---
            [
                'name' => 'iPhone 15 Pro',
                'slug' => Str::slug('iPhone 15 Pro'),
                'category_id' => 1,
                'description' => 'Flagship smartphone from Apple with A17 Pro chip.',
                'gpu' => 'Apple GPU 6-core',
                'cpu' => 'A17 Pro Hexa-core',
                'ram' => '8GB',
                'rom' => '256GB',
                'connection_port' => 'USB-C',
                'camera' => '48MP + 12MP',
                'battery' => '3274mAh',
                'monitor_size' => '6.1 inch',
                'monitor_resolution' => '2556x1179',
                'isArrival' => true,
                'price' => 29990000,
                'stock' => 10,
            ],
            [
                'name' => 'Samsung Galaxy S24 Ultra',
                'slug' => Str::slug('Samsung Galaxy S24 Ultra'),
                'category_id' => 1,
                'description' => 'High-end Android phone with S Pen and AI features.',
                'gpu' => 'Adreno 750',
                'cpu' => 'Snapdragon 8 Gen 3',
                'ram' => '12GB',
                'rom' => '512GB',
                'connection_port' => 'USB-C',
                'camera' => '200MP + 12MP + 10MP',
                'battery' => '5000mAh',
                'monitor_size' => '6.8 inch',
                'monitor_resolution' => '3088x1440',
                'isArrival' => true,
                'price' => 32990000,
                'stock' => 5,
            ],

            // --- Laptops ---
            [
                'name' => 'MacBook Air M3 2025',
                'slug' => Str::slug('MacBook Air M3 2025'),
                'category_id' => 2,
                'description' => 'Lightweight laptop with Apple M3 chip and Retina display.',
                'gpu' => 'Integrated 10-core GPU',
                'cpu' => 'Apple M3 8-core',
                'ram' => '16GB',
                'rom' => '512GB SSD',
                'connection_port' => '2x Thunderbolt 4, MagSafe 3',
                'camera' => '1080p FaceTime HD',
                'battery' => '52.6Wh',
                'monitor_size' => '13.6 inch',
                'monitor_resolution' => '2560x1664',
                'isArrival' => true,
                'price' => 31990000,
                'stock' => 8,
            ],
            [
                'name' => 'ASUS ROG Zephyrus G16',
                'slug' => Str::slug('ASUS ROG Zephyrus G16'),
                'category_id' => 2,
                'description' => 'Gaming laptop with RTX 4070 GPU and Intel Core i9.',
                'gpu' => 'NVIDIA RTX 4070 8GB',
                'cpu' => 'Intel Core i9-13900H',
                'ram' => '32GB',
                'rom' => '1TB SSD',
                'connection_port' => 'USB-C, HDMI, Ethernet',
                'camera' => 'FHD 1080p',
                'battery' => '90Wh',
                'monitor_size' => '16 inch',
                'monitor_resolution' => '2560x1600',
                'isArrival' => false,
                'price' => 49990000,
                'stock' => 2,
            ],

            // --- Tablets ---
            [
                'name' => 'iPad Air M2',
                'slug' => Str::slug('iPad Air M2'),
                'category_id' => 3,
                'description' => 'Apple iPad Air powered by M2 chip for work and entertainment.',
                'gpu' => 'Apple GPU 10-core',
                'cpu' => 'Apple M2',
                'ram' => '8GB',
                'rom' => '256GB',
                'connection_port' => 'USB-C',
                'camera' => '12MP Wide',
                'battery' => '28.6Wh',
                'monitor_size' => '10.9 inch',
                'monitor_resolution' => '2360x1640',
                'isArrival' => false,
                'price' => 18990000,
                'stock' => 6,
            ],
            [
                'name' => 'Samsung Galaxy Tab S9 Ultra',
                'slug' => Str::slug('Samsung Galaxy Tab S9 Ultra'),
                'category_id' => 3,
                'description' => 'Large AMOLED tablet with S Pen and IP68 water resistance.',
                'gpu' => 'Adreno 740',
                'cpu' => 'Snapdragon 8 Gen 2',
                'ram' => '12GB',
                'rom' => '512GB',
                'connection_port' => 'USB-C 3.2',
                'camera' => '13MP + 8MP',
                'battery' => '11200mAh',
                'monitor_size' => '14.6 inch',
                'monitor_resolution' => '2960x1848',
                'isArrival' => false,
                'price' => 27990000,
                'stock' => 4,
            ],

            // --- Accessories ---
            [
                'name' => 'Apple Watch Series 10',
                'slug' => Str::slug('Apple Watch Series 10'),
                'category_id' => 4,
                'description' => 'Smartwatch with health sensors and improved display.',
                'gpu' => 'Apple GPU',
                'cpu' => 'S10 Dual-core',
                'ram' => '2GB',
                'rom' => '64GB',
                'connection_port' => 'Wireless charging',
                'camera' => null,
                'battery' => '308mAh',
                'monitor_size' => '2 inch',
                'monitor_resolution' => '410x502',
                'isArrival' => true,
                'price' => 13990000,
                'stock' => 12,
            ],
            [
                'name' => 'AirPods Pro 2',
                'slug' => Str::slug('AirPods Pro 2'),
                'category_id' => 4,
                'description' => 'Wireless earbuds with ANC and MagSafe charging.',
                'gpu' => 'Apple H2 chip',
                'cpu' => 'Apple H2',
                'ram' => null,
                'rom' => null,
                'connection_port' => 'Lightning / MagSafe',
                'camera' => null,
                'battery' => '6 hours (earbuds)',
                'monitor_size' => null,
                'monitor_resolution' => null,
                'isArrival' => false,
                'price' => 6990000,
                'stock' => 15,
            ],
            [
                'name' => 'Logitech MX Master 4S',
                'slug' => Str::slug('Logitech MX Master 4S'),
                'category_id' => 4,
                'description' => 'Ergonomic wireless mouse for productivity and creators.',
                'gpu' => null,
                'cpu' => null,
                'ram' => null,
                'rom' => null,
                'connection_port' => 'USB-C charging',
                'camera' => null,
                'battery' => '70 days per charge',
                'monitor_size' => null,
                'monitor_resolution' => null,
                'isArrival' => false,
                'price' => 2990000,
                'stock' => 9,
            ],
            [
                'name' => 'Anker 737 Power Bank',
                'slug' => Str::slug('Anker 737 Power Bank'),
                'category_id' => 4,
                'description' => 'Powerful 140W USB-C power bank supporting PD 3.1.',
                'gpu' => null,
                'cpu' => null,
                'ram' => null,
                'rom' => null,
                'connection_port' => 'USB-C x2, USB-A x1',
                'camera' => null,
                'battery' => '24000mAh',
                'monitor_size' => null,
                'monitor_resolution' => null,
                'isArrival' => false,
                'price' => 4990000,
                'stock' => 0,
            ],
        ];

        foreach ($products as $product) {
            $product['status'] = $product['stock'] == 0 ? 'out_of_stock' : 'in_stock';
            Product::create($product);
        }
    }
}
